### ISSUE TITLE
Error when having use_frameworks! in Podfile

### ISSUE THREAD

**Issue by juanuribeo13** [ziryanov/CCInfiniteScrolling#11]
I'm migrating an Objective-C project to Swift and I added `use_frameworks!` to my `Podfile` but then I got an error in `UIScrollView+infiniteScrolling.m` in this line `#import <UIView+TKGeometry/UIView+TKGeometry.h>`. I was able to fix it by changing it to import the module like this `@import UIView_TKGeometry;`. I uploaded the fix and is in the following pull request https://github.com/ziryanov/CCInfiniteScrolling/pull/10

**Comment by ziryanov** [comment]
merged
