### ISSUE TITLE
The spinner is not centered in iPhone 6 or 6+.

### ISSUE THREAD

**Issue by benwu7** [ziryanov/CCInfiniteScrolling#5]
The spinner is not centered in iPhone 6 or 6+. Works fine on iPhone 5s or below.

![image](https://cloud.githubusercontent.com/assets/1617474/6344383/b7ae41be-bbac-11e4-9fca-1b600289804f.png)

**Comment by ziryanov** [comment]
fixed

**Comment by benwu7** [comment]
Thank you!

**Comment by mergesort** [comment]
@ziryanov I upgraded to 0.5 (by running `pod update` to the latest version), and it actually started to right-align the spinner on my iPhone 6. I wasn't seeing this before, and I downgraded back to 0.4.1, and that resolved my issue.

Thoughts?

**Comment by ziryanov** [comment]
@mergesort Try version 0.5.1 please, I guess I finally fixed it.

**Comment by mergesort** [comment]
@ziryanov Yep, all good, thanks!
