### ISSUE TITLE
Update pod spec at Cocoapods

### ISSUE THREAD

**Issue by FelipeDocil** [ziryanov/CCInfiniteScrolling#8]
I see you have `0.5.2` released here but Cocoapods is not referencing that, so I guess you forgot to run 

`pod trunk push CCInfiniteScrolling.podspec`

For more information: https://guides.cocoapods.org/making/specs-and-specs-repo.html

**Comment by ziryanov** [comment]
Thanks for reminder. Pushed 0.5.3
